@url = http://localhost:3333

### BASE
{{url}}

### EMPLOYEES
{{url}}/employees

### ADD EMPLOYEE
POST {{url}}/employee
content-type: application/json

{
	"employee": {
		"firstName": "hans",
		"lastName": "reinerson",
		"title": "Developer",
		"age": "22" 
	}
}